apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infinilapse
  name: infinilapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinilapse
  template:
    metadata:
      labels:
        app: infinilapse
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: device
                    operator: In
                    values:
                      - camera
#            - labelSelector:
#                matchExpressions:
#                  - key: name
#                    operator: In
#                    values:
#                      - web-app
#            nodeSelectorTerms:
#            – matchExpressions:
#              – key: device
#                operator: in
#                values:
#                – camera
#      nodeSelector:
#        camera: "true"
      containers:
      - name: cam-gbucket-dgraph
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TIMELAPSE_INTERVAL_MINS
            value: "15"
          - name: 	MQTT_BROKER_HOST
            value: "pop-os.local"
          - name: MQTT_BROKER_PORT
            value: "1884"
          - name: OUTPUT_DIR_WEBCAMS
            value: "/data/img/webcams"
          - name: TZ
            value: America/Denver
        image: nargetdev/cam-gbucket-dgraph:0.4.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: test-volume
      - name: dslr-gbucket-dgraph
        env:
          - name: binary_path
            value: "/dslr_capture_loop"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TIMELAPSE_INTERVAL_MINS
            value: "15"
#          - name: 	MQTT_BROKER_HOST
#            value: "192.168.1.51"
#          - name: MQTT_BROKER_PORT
#            value: "1884"
          - name: TZ
            value: America/Denver
        image: nargetdev/dslr-gbucket-dgraph:0.0.0
        command: [ "/dslr_capture_loop" ]
#        args: []
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data
            name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /data
          # this field is optional
          type: Directory
#      nodeName: blackfin

