apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nonvolatile-photos-volume
spec:
#  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
