apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: infinilapse-daemon
  labels:
    k8s-app: infinilapse-daemon
spec:
  selector:
    matchLabels:
      name: infinilapse-daemon
  template:
    metadata:
      labels:
        name: infinilapse-daemon
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        device: camera
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: dslr-gbucket-dgraph
#          resources:
#            limits:
#              cpu: 800m
#              memory: 1Gi
#            requests:
#              cpu: 400m
#              memory: 500Mi
          env:
            - name: TZ
              value: America/Denver
            - name: binary_path
              value: "/dslr_capture_loop"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TIMELAPSE_INTERVAL_MINS
              value: "15"
            - name: COMPILE
              value: "false"
            - name: DSLR_CAPTURE
              value: "true"
            - name: WEBCAM_CAPTURE
              value: "true"
            - name: COMPILE_NOW
              value: "false"
            - name: EXPOSURE_0
              value: "140"
            - name: EXPOSURE_2
              value: "200"
            - name: EXPOSURE_4
              value: "40"
            - name: EXPOSURE_6
              value: "12"
            - name: EXPOSURE_8
              value: "60"
            # REQUIRED - So I can test some of this stuff locally.
            - name: I_AM_EMBEDDED
              value: "true"
          #          - name: 	MQTT_BROKER_HOST
          #            value: "192.168.1.51"
          #          - name: MQTT_BROKER_PORT
          #            value: "1884"
          image: nargetdev/infinilapse:arm64-1.1.2
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /data
              name: photos-volume
#      volumes:
#        - name: photos-volume
#          hostPath:
#            # directory location on host
#            path: /data
#            # this field is optional
#            type: Directory
      volumes:
        - name: photos-volume
          nfs:
            # URL for the NFS server
            server: 192.168.1.35
            path: /volume2/SSD_500GB/infiniShare
      terminationGracePeriodSeconds: 30
